# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ім’я клієнта')),
                ('type_cl', models.CharField(choices=[('юридична особа', 'юридична особа'), ('фізична особа', 'фізична особа'), ('банк', 'банк')], max_length=30, verbose_name='Тип клієнта')),
            ],
            options={
                'verbose_name_plural': 'Клієнти',
                'verbose_name': 'Клієнт',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateField(verbose_name='Дата укладення договору')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name_plural': 'Укладені договори',
                'verbose_name': 'Укладений договір',
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_credit', models.DateField(verbose_name='Дата визначення суми')),
                ('all_sum', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Вся сума')),
            ],
            options={
                'verbose_name_plural': 'Суми в кредитному портфелі',
                'verbose_name': 'Сума в кредитному портфелі',
            },
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Назва депозиту')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Відсоткова ставка')),
                ('duration', models.IntegerField(choices=[(3, 'Короткостроково, 3 місяці'), (6, 'Короткостроково, 6 місяців'), (12, 'Довгостроково, 12 місяців')], verbose_name='Тривалість')),
            ],
            options={
                'verbose_name_plural': 'Депозитні програми',
                'verbose_name': 'Депозитна програма',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('document', models.CharField(max_length=150, verbose_name='Документ')),
                ('id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='Клієнт')),
                ('id_contracts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contracts', verbose_name='Договір')),
                ('id_credits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Credits', verbose_name='Сума кредиту')),
            ],
            options={
                'verbose_name_plural': 'Звіти',
                'verbose_name': 'Звіт',
            },
        ),
        migrations.CreateModel(
            name='SWOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swot_attr', models.CharField(max_length=100, verbose_name='Swot attribute')),
                ('swot_type', models.CharField(choices=[('S', 'Strengths'), ('W', 'Weaknesses'), ('O', 'Opportunities'), ('T', 'Threats')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'SWOT analysis',
                'verbose_name': 'SWOT',
            },
        ),
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва валюти')),
                ('sign', models.CharField(max_length=5, verbose_name='Умовне позначення')),
            ],
            options={
                'verbose_name_plural': 'Валюти',
                'verbose_name': 'Валюта',
            },
        ),
        migrations.AddField(
            model_name='deposits',
            name='id_valuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Valuta', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='id_deposits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Deposits', verbose_name='Депозит'),
        ),
    ]
